### ISSUE TITLE
Broken Books

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/epub2pwa#3]
See https://www.himalayanacademy.com/media/books/ten-tales-about-religious-life/web/cover.html

When here, if I click the menu, it jumps to a page other than the TOC. 

If you go anywhere in the book past the real TOC: https://www.himalayanacademy.com/media/books/ten-tales-about-religious-life/web/table_of_contents.html

by hitting the 'next' arrrow, then you get broken pages that say this:

_This page contains the following errors:
error on line 36 at column 17: Specification mandates value for attribute defer
Below is a rendering of the page up to the first error.
Ten Tales About Religious Life_

I've encountered other books with similar issues. I didn't note which ones, but I will next time I come across them.

**Comment by soapdog** [comment]
Book: **Ten Tales of Religious Life**

The correct processing of the book failed due to two mistakes:

* Whoever made the epub tagged the HTML files inside the epub as XHTML but they are not valid XHTML files. Browsers are refusing to render them.
* The automatic identification of the table of contents is failing and detecting the introduction as TOC.

I am fixing both issues right now.

**Comment by soapdog** [comment]
I've fixed that book but in doing so, I noticed that the TOC generation code had a problem. Basically, we detect the TOC by counting links on the page. The page with most links is the table of contents. 

Unfortunately, I've added code to add a link to the end of every paragraph so that we can share those links and be able to direct readers to specific content. That paragraph adding code executed before the TOC finding code causing problems as now, the longest page (the one with more paragraphs) would be labeled the table of content.

This is probably affecting multiple books so I will re-export them all right now.

cc @Brahmanathaswami

**Comment by soapdog** [comment]
Books exported. 

The **Ten Tales of Religious Life** is at https://www.himalayanacademy.com/media/books/ten-tales-about-religious-life/web/cover.html

I am going ahead and moving it to the main site. Be aware that it will be cached for everyone who read it, they will need to refresh the pages to see the new data as the current PWA caches each page viewed.

**Comment by soapdog** [comment]
Books exported. 

The **Ten Tales of Religious Life** is at https://www.himalayanacademy.com/media/books/ten-tales-about-religious-life/web/cover.html

I am going ahead and moving it to the main site. Be aware that it will be cached for everyone who read it, they will need to refresh the pages to see the new data as the current PWA caches each page viewed.
