### ISSUE TITLE
Broken View on Dev Site

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/epub2pwa#7]
https://dev.himalayanacademy.com/view/dancing-with-siva

all the book appear this way

This view is "breaking" 

/home/devhap/public_html/system/application/ha/views/media/book-details.lc

**Comment by soapdog** [comment]
Swami,

I don't see anything wrong in the view. This might already be fixed due to #5 

Also, this is not a descriptive issue. You say the view is breaking but you don't show or tell what is broken. Please the next time you make an issue, you need to be more descriptive. If you're talking about a view, then take screenshots, annotate them with what is broken. The way it is here it is almost as saying _"the site is broken"_, it may as well be but it doesn't help. I think this is already fixed due to the work in #5.
